-- Remove the CHECK constraint on entity_relationships.type
-- so that users can create custom relationship names in the People Atlas.

-- The constraint name is auto-generated by Postgres since it wasn't named in the original CREATE TABLE.
-- Usually it's named 'entity_relationships_type_check'
ALTER TABLE entity_relationships DROP CONSTRAINT IF EXISTS entity_relationships_type_check;

-- Also try to drop it if it has a generic name (in case the above doesn't work)
DO $$
DECLARE
    r RECORD;
BEGIN
    FOR r IN (
        SELECT conname
        FROM pg_constraint
        WHERE conrelid = 'entity_relationships'::regclass
          AND contype = 'c' -- Check constraint
    ) LOOP
        -- Since there's another check constraint for from != to, we only drop the one related to 'type'
        -- but just dropping the known name is usually enough. If needed, we drop all and recreate the from!=to one.
        IF r.conname LIKE '%type%' THEN
            EXECUTE 'ALTER TABLE entity_relationships DROP CONSTRAINT ' || quote_ident(r.conname);
        END IF;
    END LOOP;
END;
$$;
